### ISSUE TITLE
incorrect implementation or documentation of `DataStore.get()`

### ISSUE THREAD

**Issue by jlouros** [APIDevTools/swagger-express-middleware#140]
`DataStore.get()` implementation or documentation needs to be fixed.
From the provided documentation, the expectation of calling `DataStore.get('/pets/dogname')` should return the actual resource.
Using a callback seems to be unnecessary, but even if that's the desired implementation, `get()` should return a boolean indicating if the resource was found or not.

https://github.com/APIDevTools/swagger-express-middleware/blob/654be62cc1f228ca6cf7c840cf3eb5ef5a3511b0/lib/data-store/index.js#L27-L52

**Comment by JamesMessinger** [comment]
I'm not sure I understand.  The `DataStore.get()` method is asynchronous, so the result can only be returned via the callback.  It can't return the result synchronously.

**Comment by jlouros** [comment]
Maybe it's a known convention in NodeJS based projects, but I could not infer `DataStore.get()` was asynchronous just by reading the documentation. 

Maybe further describing that `callback` param is required would be enough. At the same time, the first statement of the documentation for this method is *Returns the given resource*, which I assumed the function returned. Instead the callback should state that.

**Comment by JamesMessinger** [comment]
Yeah, [the Callback Pattern](https://medium.com/yld-engineering-blog/the-callback-pattern-8d12d7759a29), and specifically the [Error-First Callback Pattern](http://fredkschott.com/post/2014/03/understanding-error-first-callbacks-in-node-js/) are common conventions in NodeJS.   Back when Node was first created, the `async` and `await` keywords didn't exist, and JavaScript promises weren't standardized yet, so the Error-First Callback Pattern was adopted.   At some point I may rewrite swagger-express-middleware to use `async`/`await` instead of callbacks, now that `async`/`await` is widely supported.  But in the meantime, you can use [`util.promisify()`](https://nodejs.org/dist/latest-v8.x/docs/api/util.html#util_util_promisify_original) or a library like [thenify](https://www.npmjs.com/package/thenify) if you want.
