### ISSUE TITLE
ETA for 3.0?

### ISSUE THREAD

**Issue by RusseII** [APIDevTools/swagger-express-middleware#158]
Is there any type of estimate for when 3.0 will be out of alpha and ready for production?

Just a general time frame
1-3 months?
3-6 months?
6-12 months?
12+ months?

Thanks!

**Comment by JamesMessinger** [comment]
I had originally planned to release a v3 of Swagger Express Middleware with up-to-date dependencies and support for both Swagger 2.0 and OpenAPI 3.0.  But that has proved too challenging, for a few reasons:

- Supporting both the 2.0 and 3.0 specs consistently is very difficult

- Swagger Express Middleware is very complex and each middleware depends so tightly on the other ones that changing anything in one middleware often causes something to break in a different middlware

- I haven't had time to make any progress on the v3 branch for several months because my job has had me focused on other, unrelated stuff.

However, my focus at work is about to change back to Swagger Express Middleware, so I'll be able to start devoting time to this again.  And my new plan is to split this package up into separate packages that are well-contained and independent from each other.  I will focus on supporting OpenAPI 3.0, but may also create an adapter package that adds support for Swagger 2.0 as well.

By creating smaller modules, I'll also be able to release them sooner.  Rather than having to wait until _everything_ is totally done, I'll be able to release each package as soon as it's done.  And since many people only use a subset of Swagger Express Middleware's functionality, those people will be able to switch to the new packages as soon as the subset that they need are done.

**Comment by ctippur** [comment]
Is there a workaround for this? Do I need to mive back to swagger 2.0?

**Comment by orcas-mgleich** [comment]
New information?

**Comment by hpl002** [comment]
> Is there a workaround for this? Do I need to move back to swagger 2.0?

im sure there exists a few projects which have attempted to tackle this, ive had some luck with <https://www.npmjs.com/package/openapi-validator-middleware>
