### ISSUE TITLE
Can swagger-express-middleware mock based on example response?

### ISSUE THREAD

**Issue by gauravphoenix** [APIDevTools/swagger-express-middleware#57]
First of all, I am thankful such project exists.

My response definition looks like this- 

```
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Account"
              }
            },
            "examples": {
              "application/json": [
                {
                  "id": 123,
                  "name": "dev-account"
                },
                {
                  "id": 456,
                  "name:": "prod-account"
                }
              ]
            }
          }
        }
```

When using swagger-express-middleware I was hoping that when I make API call I will get example response back but I get back an empty array. What can I do to make sure I get example response back?

**Comment by whq731** [comment]
+1

**Comment by BigstickCarpet** [comment]
The Swagger Spec allows 3 different ways to provide default/example responses.  It's important to distinguish between the three:

**1.** `responses.[code].examples`
**Spec:** [here](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#response-object) and [here](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#exampleObject)
This object allows you to provide example responses for different MIME types.  This is a new feature that was added to the Swagger Spec since the last release of Swagger Express Middleware, so it's **not yet supported**.

**2.** `responses.[code].schema.example`
**Spec:** [here](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#fixed-fields-13)
This object allows you to provide an example of a schema.  Swagger Express Middleware will automatically use your `example` as the response if there is no other data available, as [described here](https://github.com/BigstickCarpet/swagger-server/blob/master/samples/docs/yaml.md#defaultexample-responses)

**3.** `responses.[code].schema.default`
**Spec:** [here](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#schema-object)
This object allows you to provide a default value for a schema.  Swagger Express Middleware treats this exactly the same as the `response.[code].schema.example` property, so it will use it as the response if there is no other data available.

**Comment by gauravphoenix** [comment]
@BigstickCarpet thanks so much for quick response. I'll go ahead and use responses.[code].schema.example. 

On a side node, I wonder what is the real value of responses.[code].examples.

**Comment by gitms12** [comment]
I understand that `examples` is currently not supported, but why is the swagger-parser failing if `examples` is in the YAML? From the projects code, it looks like the underlying schema for Swagger contains it, so I'm wondering why it is not parsed correctly but just ignored by the middleware?

`SyntaxError: Data does not match any schemas from "oneOf"
Data path: "/paths/...get/responses/200"
Schema path: "/properties/paths/patternProperties/^~1/properties/get/properties/
responses/patternProperties/^([0-9]{3})$|^(default)$/oneOf"
`

**Comment by Fabriciu** [comment]
Couldn't make it work using default.

I defined my yaml. This is a part of the code:
```
      responses:
        "200":
          description: successful operation
          schema:
            $ref: "#/definitions/user"
        404:
          description: User not found.
          schema:
            type: object
            properties:
              type:
                type: string
                example: "error"
              status:
                type: string
                example: "403"
              code:
                type: string
                example: "-20001"
              message:
                type: string
                example: "User not found"
              responseId:
                type: string
                example: "Id-1-2-3"
            default:
              type: "error"
              status: "404"
              code: "-20001"
              message: "User not found"
              responseId: "Id-1-2-3"
```

When I call the API, the middleware returns HTTP 404 and the trace:

```
Error: /user Not Found
<br> &nbsp; &nbsp;at ono (/appl/applications/nodeJS/lib/node_modules/swagger-express-middleware/node_modules/ono/lib/index.js:62:17)
<br> &nbsp; &nbsp;at /appl/applications/nodeJS/lib/node_modules/swagger-express-middleware/lib/mock/query-resource.js:34:15
<br> &nbsp; &nbsp;at doCallback (/appl/applications/nodeJS/lib/node_modules/swagger-express-middleware/lib/data-store/index.js:303:5)
<br> &nbsp; &nbsp;at /appl/applications/nodeJS/lib/node_modules/swagger-express-middleware/lib/data-store/index.js:49:7
<br> &nbsp; &nbsp;at Immediate.&lt;anonymous&gt; (/appl/applications/nodeJS/lib/node_modules/swagger-express-middleware/lib/data-store/index.js:290:5)
<br> &nbsp; &nbsp;at Immediate.immediate._onImmediate (timers.js:440:18)
<br> &nbsp; &nbsp;at processImmediate [as _immediateCallback] (timers.js:383:17)
```

Any idea?

Thanks!

**Comment by bmakuh** [comment]
@Fabriciu any luck on this? I'm running into the same thing.

**Comment by benz-sc** [comment]
great library!
I am wondering whether taking the example from `definitions.[entity].example` as already implemented by swagger-ui should also be implemented?
