### ISSUE TITLE
Ability to generate mock data

### ISSUE THREAD

**Issue by JamesMessinger** [APIDevTools/swagger-express-middleware#8]
Right now, Swagger Express Middleware focuses on providing mock _implementations_ rather than mock _data_, but there's no reason it couldn't do both.   It already does a _little_ bit of mock-data generation to [set HTTP headers](https://github.com/BigstickCarpet/swagger-express-middleware/blob/e80fe2f2c232aee33199fc2166a6add2352a19a9/lib/mock/index.js#L171-L172) and to [assign unique IDs when new resources are created](https://github.com/BigstickCarpet/swagger-express-middleware/blob/38b6a46c7f042020b91186488917122f6b500b7a/lib/mock/edit-collection.js#L157-L160), but ideally the [DataStore class](https://github.com/BigstickCarpet/swagger-express-middleware/blob/38b6a46c7f042020b91186488917122f6b500b7a/docs/exports/DataStore.md) would have the ability to automatically populate itself fully with mock data based on the JSON Schemas defined in the Swagger API.

**Comment by BigstickCarpet** [comment]
The [current mock-data generation code](https://github.com/BigstickCarpet/swagger-express-middleware/blob/c588f834cdf5b62e60ae21dec7771b2a07458553/lib/helpers/json-schema.js#L143-L148) is far too simplistic and will need to be enhanced.  

Currently, it just generates random values based on the data type, min/max length, and min/max values specified in the JSON Schema.  This should be enhanced to use a library such as [Faker](https://www.npmjs.com/package/faker) to generate more realistic mock data.  This way, a property named "firstName" would have mock data like "John", "David", or "Sarah", rather than a random string like "a9d72jdk1jdhqjd187snd".  We should also provide some mechanism for API authors to specify the type of data to generate, since we won't always be able to determine based on the property name.

Also, we need to enhance the code to support complex JSON schemas.  Currently, it supports primitive types (string, number, date, etc.), arrays, and objects.  But it _doesn't_ support JSON schema values such as `oneOf`, `anyOf`,  `allOf`, `patternProperties`, etc.

**Comment by brettdh** [comment]
Just chiming in with a note that I ran into the lack of `oneOf` support in the mock middleware today with a Swagger spec from [an Oracle API](https://docs.oracle.com/en/cloud/saas/service/18a/cxsvc/swagger.json).

I _may_ have time to work on this, but I'm not at all sure about that.

**Comment by brettdh** [comment]
In my case, however, it turns out that every array type is actually just `[<supported type>, "null"]`, so I can work around this limitation by replacing that with just the supported type before passing the schema to the mock middleware. :tada:
